// Design tokens — single source of truth for all visual properties
export const tokens = {
  colors: {
    bgPrimary: "var(--color-bg-primary)",
    bgSecondary: "var(--color-bg-secondary)",
    bgTertiary: "var(--color-bg-tertiary)",
    bgCard: "var(--color-bg-card)",
    bgCardHover: "var(--color-bg-card-hover)",
    bgOverlay: "var(--color-bg-overlay)",
    textPrimary: "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    accentPrimary: "var(--color-accent-primary)",
    accentPrimaryLight: "var(--color-accent-primary-light)",
    accentPrimaryMuted: "var(--color-accent-primary-muted)",
    accentSuccess: "var(--color-accent-success)",
    accentWarning: "var(--color-accent-warning)",
    accentError: "var(--color-accent-error)",
    border: "var(--color-border)",
    borderLight: "var(--color-border-light)",
  },
  spacing: {
    xs: "var(--space-xs)",
    sm: "var(--space-sm)",
    md: "var(--space-md)",
    lg: "var(--space-lg)",
    xl: "var(--space-xl)",
    "2xl": "var(--space-2xl)",
    "3xl": "var(--space-3xl)",
  },
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    full: "var(--radius-full)",
  },
  typography: {
    fontFamily: "var(--font-primary)",
    fontMono: "var(--font-mono)",
    sizeXs: "clamp(0.625rem, 0.5rem + 0.25vw, 0.75rem)",
    sizeSm: "clamp(0.75rem, 0.65rem + 0.3vw, 0.875rem)",
    sizeBase: "clamp(0.875rem, 0.75rem + 0.35vw, 1rem)",
    sizeLg: "clamp(1rem, 0.85rem + 0.5vw, 1.25rem)",
    sizeXl: "clamp(1.25rem, 1rem + 0.75vw, 1.75rem)",
    size2xl: "clamp(1.5rem, 1.15rem + 1vw, 2.25rem)",
    size3xl: "clamp(2rem, 1.5rem + 1.5vw, 3rem)",
  },
  shadows: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    glow: "var(--shadow-glow)",
  },
  transitions: {
    fast: "150ms ease-out",
    normal: "250ms ease-out",
    slow: "400ms ease-out",
    spring: "500ms cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;
